// Generated by `cairn webmcp` from commit "24cf2ed" at 2026-09-02T21:43:37.276Z.
// Do not edit by hand — regenerate instead (`npx cairn webmcp <dir>` after
// a fresh `cairn build`, whenever the app's real actions change).
//
// Registers this app's own real, traced actions
// (https://webmachinelearning.github.io/webmcp/) so ANY agent that
// understands the standard — not just Cairn — can discover and call them
// directly. No Cairn import here on purpose: this keeps working even in an
// app that later removes Cairn entirely, and costs nothing on a browser
// that doesn't implement WebMCP yet (the overwhelming majority right now —
// registerTool() is checked for and simply skipped if absent).
"use client";

import { useEffect } from "react";

export function CairnWebMcpTools() {
  useEffect(() => {
    const modelContext = (document as unknown as { modelContext?: any }).modelContext;
    if (!modelContext?.registerTool) return;

    let unregistered = false;
    const handles: { remove?: () => void }[] = [];
    const register = (tool: unknown) => {
      void modelContext
        .registerTool(tool)
        .then((registered: { remove?: () => void }) => {
          if (unregistered) registered?.remove?.();
          else handles.push(registered);
        })
        .catch(() => {
          // A page without a real WebMCP implementation, or a tool name
          // this app already registered some other way — nothing to do.
        });
    };

    register({
      name: "invoices-create-invoice",
      description: "Creates a new invoice by sending a POST request to `/api/invoices` and then adds it to the invoice list.",
      inputSchema: { type: "object", properties: {} },
      execute: async () => {
        const res = await fetch("/api/invoices", { method: "POST", credentials: "same-origin" });
        return { ok: res.ok, status: res.status };
      },
    });

    return () => {
      unregistered = true;
      for (const handle of handles) handle?.remove?.();
    };
  }, []);

  return null;
}
