// Turns a manifest into human-readable Markdown docs. The content already
// exists in the manifest — this is just formatting, no LLM call.

import type { Manifest } from "@cairn/core";

export function generateDocsMarkdown(manifest: Manifest): string {
  const sections: string[] = [
    `# App Reference`,
    ``,
    `Generated by \`cairn docs\` from commit \`${manifest.commit}\` at ${manifest.generatedAt}. Do not edit by hand — regenerate instead.`,
    ``,
  ];

  const pages = [...manifest.pages].sort((a, b) => a.route.localeCompare(b.route));
  for (const page of pages) {
    sections.push(`## ${page.title} (\`${page.route}\`)`, ``, page.purpose, ``, `**When to use:** ${page.whenToUse}`, ``);

    if (page.elements.length > 0) {
      sections.push(`| Element | Does |`, `|---|---|`);
      for (const el of page.elements) {
        sections.push(`| ${el.label} | ${el.does} |`);
      }
      sections.push(``);
    }
  }

  if (manifest.dead.length > 0) {
    sections.push(`## Dead code`, ``, `Not reachable from any route — safe-ish to remove:`, ``);
    for (const file of [...manifest.dead].sort()) sections.push(`- \`${file}\``);
    sections.push(``);
  }

  if (manifest.conflicts.length > 0) {
    sections.push(`## Naming conflicts resolved during the last build`, ``);
    for (const c of manifest.conflicts) {
      sections.push(`- Between ${c.candidates.map((f) => `\`${f}\``).join(" and ")}, chose \`${c.chose}\` — ${c.reason}.`);
    }
    sections.push(``);
  }

  return sections.join("\n");
}
