// The "one command, any platform" piece: for a non-Next project, Cairn's
// backend (cairn-server.cjs) and the realtime voice relay (cairn-realtime)
// are separate processes from the app's own dev server — there's no shared
// framework runtime to hook into the way `cairn-realtime --with "next dev"`
// piggybacks on Next. Rather than asking the user to open three terminals
// (found live to be exactly the kind of step nobody remembers, same class
// of bug as the "realtime relay isn't running" gap `cairn-realtime --with`
// itself was built to close), this generates one small script that spawns
// all of them together and tears all of them down together, then wires it
// in as the project's own "dev" script — `npm run dev` becomes the one
// command, same as it already is for Next.

export interface OrchestratorCommand {
  label: string;
  command: string;
}

/** Builds a real (unminified, easy-to-read-if-it-fails) Node script that
 * spawns every given command as a child process with inherited stdio (so
 * output/errors from the app, the Cairn backend, and the realtime relay
 * all interleave in the same terminal, prefixed by label), and — the part
 * a naive `command1 & command2 & command3` shell one-liner doesn't do
 * reliably — kills every sibling the moment ANY one of them exits or the
 * whole thing receives Ctrl+C, so a crashed backend doesn't leave the
 * frontend dev server orphaned and still bound to its port. */
export function buildOrchestratorScript(commands: OrchestratorCommand[]): string {
  const entries = commands.map((c) => `  { label: ${JSON.stringify(c.label)}, command: ${JSON.stringify(c.command)} },`).join("\n");
  return `// cairn-dev.cjs — generated by \`cairn setup\`. Runs your app's own dev
// command alongside the Cairn backend (and the realtime voice relay, if
// voice was set up) as one command, and stops all of them together.
// Regenerate by re-running \`cairn setup\`; safe to edit by hand too.
const { spawn } = require("node:child_process");

const commands = [
${entries}
];

const children = commands.map(({ label, command }) => {
  const child = spawn(command, { shell: true, stdio: "pipe" });
  const prefix = \`[\${label}]\`;
  child.stdout.on("data", (buf) => process.stdout.write(buf.toString().split("\\n").filter(Boolean).map((l) => \`\${prefix} \${l}\\n\`).join("")));
  child.stderr.on("data", (buf) => process.stderr.write(buf.toString().split("\\n").filter(Boolean).map((l) => \`\${prefix} \${l}\\n\`).join("")));
  return child;
});

let shuttingDown = false;
function shutdown(exitCode) {
  if (shuttingDown) return;
  shuttingDown = true;
  for (const child of children) {
    try {
      child.kill();
    } catch {
      // already exited
    }
  }
  process.exitCode = exitCode;
}

children.forEach((child, i) => {
  child.on("exit", (code) => {
    if (!shuttingDown) console.error(\`[cairn-dev] \${commands[i].label} exited (code \${code}) — stopping everything else.\`);
    shutdown(code ?? 1);
  });
});

process.on("SIGINT", () => shutdown(0));
process.on("SIGTERM", () => shutdown(0));
`;
}
